import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marketplace de servicos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Marketplace de servicos</h1>
        <Link href="/services/offer">
          <a>Crie sua oferta!</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
